FROM node:20-alpine

# Nastavi delovno mapo
WORKDIR /app

# Produkcijski način
ENV NODE_ENV=production

# Kopiraj samo metapodatke za odvisnosti
COPY package.json package-lock.json ./

# Namesti samo production dependencies
RUN npm ci --omit=dev

# Kopiraj ARTEFAKT (build output)
COPY dist ./dist

# (če rabiš še kakšne runtime datoteke, jih dodaš tukaj)
# COPY prisma ./prisma

# Izpostavi port (prilagodi, če ni 3000)
EXPOSE 3000

# Zaženi aplikacijo
CMD ["node", "dist/index.js"]
